name: Reusable workflow example

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}

jobs:
  example_job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
    steps:
      - id: step1
        run: echo "firstword=${{ inputs.message }}" >> $GITHUB_OUTPUT
      
