name: Reusable workflow example

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ inputs.message }}

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "firstword=hello!"
      
